In [ ]:
import numpy as np
lst = [1, 2, 3, 4, 5] # list of integers
arr = np.array(lst)
print(arr)

[1 2 3 4 5]


In [9]:
mat = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array (matrix)
print(mat)
print(mat.shape)
print(mat.ndim)
print(mat.size)
print(mat.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [10]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([10, 20, 30, 40, 50])
print(a + b)          # Element-wise addition
print(a - b)          # Element-wise subtraction
print(a * b)          # Element-wise multiplication
print(a / b)          # Element-wise division
print(a ** 2)        # Element-wise exponentiation
print(np.sqrt(a))    # Element-wise square root
print(np.log(a))     # Element-wise natural logarithm
print(np.sin(a))     # Element-wise sine

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [12]:
#matrix multiplication example
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
C = np.dot(A, B)
print(C)  
print(A.dot(B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [13]:
#matrix operations
print(np.transpose(A))  # Transpose of matrix A
a=np.array([1,2,3,4,5,6])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))

[[1 4]
 [2 5]
 [3 6]]
3.5
3.5
1.707825127659933
21
1
6


In [17]:
# [1,2,3,4,5,6] reshaped to 2x3 matrix
arr=a.reshape((2,3))
print(arr)

print(arr.flatten())  # Flatten the 2D array back to 1D


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [19]:
#stack and filtter example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.array([7, 8, 9])
print(np.vstack((a, b, c)))  # Vertical stack
print(np.hstack((a, b, c)))  # Horizontal stack
arr=np.array([10, 15, 20, 25, 30, 35])
print(arr[arr>20])  # Filter elements greater than 20

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[25 30 35]


In [20]:
#view vs copy
original = np.array([1, 2, 3, 4, 5])
view_arr = original.view()
copy_arr = original.copy()
original[0] = 99
print("Original:", original)    # [99  2  3  4  5]
print("View:", view_arr)        # [99  2  3  4  5]
print("Copy:", copy_arr)        # [1  2  3  4  5]

Original: [99  2  3  4  5]
View: [99  2  3  4  5]
Copy: [1 2 3 4 5]
