In [ ]:
import numpy as np
lst = [1, 2, 3, 4, 5] # list of integers
arr = np.array(lst)
print(arr)

[1 2 3 4 5]


In [9]:
mat = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array (matrix)
print(mat)
print(mat.shape)
print(mat.ndim)
print(mat.size)
print(mat.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [10]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([10, 20, 30, 40, 50])
print(a + b)          # Element-wise addition
print(a - b)          # Element-wise subtraction
print(a * b)          # Element-wise multiplication
print(a / b)          # Element-wise division
print(a ** 2)        # Element-wise exponentiation
print(np.sqrt(a))    # Element-wise square root
print(np.log(a))     # Element-wise natural logarithm
print(np.sin(a))     # Element-wise sine

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [12]:
#matrix multiplication example
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
C = np.dot(A, B)
print(C)  
print(A.dot(B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [13]:
#matrix operations
print(np.transpose(A))  # Transpose of matrix A
a=np.array([1,2,3,4,5,6])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))

[[1 4]
 [2 5]
 [3 6]]
3.5
3.5
1.707825127659933
21
1
6


In [17]:
# [1,2,3,4,5,6] reshaped to 2x3 matrix
arr=a.reshape((2,3))
print(arr)

print(arr.flatten())  # Flatten the 2D array back to 1D


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [19]:
#stack and filtter example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.array([7, 8, 9])
print(np.vstack((a, b, c)))  # Vertical stack
print(np.hstack((a, b, c)))  # Horizontal stack
arr=np.array([10, 15, 20, 25, 30, 35])
print(arr[arr>20])  # Filter elements greater than 20

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[25 30 35]


In [20]:
#view vs copy
original = np.array([1, 2, 3, 4, 5])
view_arr = original.view()
copy_arr = original.copy()
original[0] = 99
print("Original:", original)    # [99  2  3  4  5]
print("View:", view_arr)        # [99  2  3  4  5]
print("Copy:", copy_arr)        # [1  2  3  4  5]

Original: [99  2  3  4  5]
View: [99  2  3  4  5]
Copy: [1 2 3 4 5]


In [2]:
#pandas
import pandas as pd
series=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [3]:
data={
    "name":["alice","roy","ani"],
    "Age":[25,30,40],
    'city':['delhi','BBSR','Mumbai']
}
df=pd.DataFrame(data)
print(df)

    name  Age    city
0  alice   25   delhi
1    roy   30    BBSR
2    ani   40  Mumbai


In [ ]:
#df=pd.read_excel(path),_csv,_json
df.head(1)


name  Age   city
0  alice   25  delhi

In [10]:
df.tail(1)

name  Age    city
2  ani   40  Mumbai

In [ ]:
df.sample(2) # take 2 random record

name  Age    city
2  ani   40  Mumbai
1  roy   30    BBSR

In [13]:
df.shape

(3, 3)

In [15]:
print(df.info)


<bound method DataFrame.info of     name  Age    city
0  alice   25   delhi
1    roy   30    BBSR
2    ani   40  Mumbai>


In [16]:
df.describe()

Age
count   3.000000
mean   31.666667
std     7.637626
min    25.000000
25%    27.500000
50%    30.000000
75%    35.000000
max    40.000000

In [17]:
df['name'].to_list()

['alice', 'roy', 'ani']

In [19]:
df[['name','Age']]

name  Age
0  alice   25
1    roy   30
2    ani   40

In [ ]:
#row operation
df.loc[2]

name       ani
Age         40
city    Mumbai
Name: 2, dtype: object

In [24]:
print(df.loc[:])

    name  Age    city
0  alice   25   delhi
1    roy   30    BBSR
2    ani   40  Mumbai


In [26]:
#filter
df[df['Age']>25]

name  Age    city
1  roy   30    BBSR
2  ani   40  Mumbai

In [28]:
#column operation
df["Age+5"]=df["Age"]+5
df

name  Age    city  Age+5
0  alice   25   delhi     30
1    roy   30    BBSR     35
2    ani   40  Mumbai     45

In [29]:
df=df.drop('Age+5',axis=1)#column
df

name  Age    city
0  alice   25   delhi
1    roy   30    BBSR
2    ani   40  Mumbai

In [30]:
df.drop(2,axis=0)#row

name  Age   city
0  alice   25  delhi
1    roy   30   BBSR